global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "fastapi"
    static_configs:
      # Замените host.docker.internal на IP, если запускаете на Linux
      - targets: ["host.docker.internal:8000"]